### ISSUE TITLE
Encryption context compatibility with AWS CLI

### ISSUE THREAD

**Issue by jwcollinge** [awslabs/aws-encryption-sdk-java#10]
There appears to be a compatibility issue between the aws CLI and the encryption sdk around the way that encryption context is formatted. This makes combining decryption of sensitive data in java apps difficult to integrate with many dev ops automation tools. 

encrypting a secret on the command line
aws kms encrypt --key-id <key-id-here> --plaintext "1\!2@3#4$5%6^7&8*9(0)-_=+" --query CiphertextBlob --encryption-context key=value --output text | base64 -d > /tmp/encrypted

and decrypting it in java

final Map<String, String> context = Collections.singletonMap("key", "value");
final CryptoResult<String, KmsMasterKey> decryptResult = crypto.decryptString(prov, ciphertext);

will give you a cipher text error because the encryption contexts don't match.

Is there a way to make this work that I'm missing or is a local java tool just for encrypting strings going to be required? Alternatively I could look at overriding the sdk serialization function to provide a cli compatible context serialization.

Thanks.

Jason

**Comment by austinmoore-** [comment]
The AWS Encryption SDK for Java is not meant to be compatible with the `aws kms` command line tool. The AWS Encryption SDK uses KMS to achieve something called envelope encryption. In short, the AWS Encryption SDK is doing more than what `aws kms encrypt` is doing.

If you'd like to decrypt something created by the `aws kms encrypt` command, look at [AWSKMSClient](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kms/AWSKMSClient.html) Java class, specifically the [decrypt method](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kms/AWSKMSClient.html#decrypt-com.amazonaws.services.kms.model.DecryptRequest-)

**Comment by austinmoore-** [comment]
@jwcollinge You probably found a different solution that works for you but, thought I'd share in case others come here with a similar question. I wrote a command-line tool that can encrypt files in the format expected by the AWS Encryption SDK. You'd be able to use it to encrypt files on the command-line and then decrypt them in your application using the AWS Encryption SDK. You can find it here if you're interested: https://github.com/aol/mrcrypt
