### ISSUE TITLE
encryptionsdk.exception.BadCiphertextException: Invalid ciphertext type.

### ISSUE THREAD

**Issue by shrikantdange1208** [awslabs/aws-encryption-sdk-java#11]
Hi Guys,
I am using aws encryption sdk to encrypt and decrypt files. I am getting "encryptionsdk.exception.BadCiphertextException: Invalid ciphertext type" in the following scenario.

I am encrypting my file using command:
aws kms encrypt --key-id keyId --region us-east-1 --plaintext file://text.txt --query CipherTextBlob --output text | base64 --decode >file.dat.encrypted.

I my code I have:
AwsCrypto awsCrypto = new AwsCrypto();
InputStream inputStream = new FileInputStream("inputfile");
final CryptoInputStream decryptingStream = awsCrypto.createDecryptingStream(provider,inputStream);
OutputStream outputStream = new FileOutputStream("outputFile");
IOUtils.copy(decryptingStream,outputStream)

Could anyone please point out what I am missing in this. I am trying to figure out the problem but I am not able to. Would appreciate any help regarding this.

Thanks.

**Comment by austinmoore-** [comment]
The AWS Encryption SDK for Java is not meant to be compatible with the `aws kms` command line tool. In short, the AWS Encryption SDK leverages KMS to provide more versatile encryption functionality than KMS alone.

If you'd like to decrypt something created by the `aws kms encrypt` command, look at [AWSKMSClient](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kms/AWSKMSClient.html) Java class, specifically the [decrypt method](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kms/AWSKMSClient.html#decrypt-com.amazonaws.services.kms.model.DecryptRequest-).

**Comment by shrikantdange1208** [comment]
Okay. I got you. I thought I was missing something. In my scenario, I want a decrypting stream which is not possible in AWSKMSClient. I will look for other solution. I will close this issue.

**Comment by austinmoore-** [comment]
@shrikantdange1208 I wrote a command-line tool, open-sourced by AOL, that's compatible with the AWS Encryption SDK. You'd be able to use it to encrypt files on the command-line that the AWS Encryption SDK can then decrypt. You can find it here if you're interested: https://github.com/aol/mrcrypt
