### ISSUE TITLE
KMS access

### ISSUE THREAD

**Issue by baratrion** [awslabs/aws-encryption-sdk-java#13]
It's a question, rather than an issue. When using `KmsMasterKeyProvider`, does it actually call KMS service each time you encrypt / decrypt data? I walked through the Concepts and Architecture documents but I'm a bit confused about the network calls AWS Encryption SDK will make when combined with AWS KMS.

Could you elaborate it more using the [String Example](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/example-code.html#example-string)?

Does it actually access KMS for the master key decryption when `encryptString` is called?

Could you somehow use `KmsMasterKeyProvider` as singleton and re-use the same master key for multiple encryptions?

**Comment by SalusaSecondus** [comment]
Yes. Every encrypt/decrypt will result in a call to KMS.

There is nothing wrong with making the KmsMasterKeyProvider a singleton and reusing it. (That's proper usage even.) However, since KMS keys live in KMS and are non-exportable, each use of them (for an encrypt/decrypt) will result in a network call to KMS.

**Comment by jamesanto** [comment]
Please correct me if I am wrong. Theoretically we reuse the data key for all the requests. I don't see a need to make calls to KMS api for each encryptXXX and decryptXXX methods. Reusing the data key could be optional.

**Comment by SalusaSecondus** [comment]
@jamesanto That is correct. The underlying implementation and data-formats were built specifically with this use in mind. However, we do not _currently_ have code available to support this use-case.
