### ISSUE TITLE
Optimizing Decryption: using MultipleProviderFactory.buildMultiProvider

### ISSUE THREAD

**Issue by pravsingh** [awslabs/aws-encryption-sdk-java#18]
Currently MultipleProviderFactory.buildMultiProvider accepts the ordered list of CMK keys.
The first CMK becomes default to generate DataKey by hitting KMS.
At the time of decryption, the same CMK is used to decrypt the encrypted DataKey.

Assuming that first CMK (passed in MultipleProviderFactory.buildMultiProvider) is always the application server's default or closest KMS region is not always true. Programmer/DevOps team can configure the CMKs in out of order. Due to this, the farthest KMS server will always get the hit even though its not in the same region as of the application server. This could lead to increase of latency.

We could optimize the list by reshuffling the CMKs list by putting the one as first element which is in the same region as of application server.

Any thoughts?

**Comment by SalusaSecondus** [comment]
We don't assume that the first master key is closest or even a KMS key. It is, however, the default key by definition and documentation. This allows developers to intelligently control which master keys are used for what purpose.  While it is entirely true that Programmers/DevOps can configure this incorrectly, they still have the ability to configure it.  If we were to reshuffle the list, we'd be removing this control from the developers and replacing it with our opinion of the best behavior (which may not be it).

**Comment by pravsingh** [comment]
agree 👍
