### ISSUE TITLE
Enhancement needed: include rotation of the datakey

### ISSUE THREAD

**Issue by pravsingh** [awslabs/aws-encryption-sdk-java#19]
Having data key rotation feature will add lots of value to the way we handle the DataKey generation.
Once DataKey is generated, it can be cached for next operations until the key gets rotated.

**Comment by bdonlan** [comment]
Data key caching (with various rotation policies) has been released as part of the 1.3.0 release.

**Comment by pravsingh** [comment]
nice. thanks
