### ISSUE TITLE
decryptData parses headers twice

### ISSUE THREAD

**Issue by creilly12** [awslabs/aws-encryption-sdk-java#2]
When using AwsCrypto.decryptData(), the headers are parsed in the DecryptionHandler() constructor as well as in the processBytes() call for the DecryptHandler. This is less than an ideal because each time the headers are parsed the data keys are decrypted. For AWS KMS keys, this means two api calls to decrypt the same data key for each call to decryptData.

**Comment by bdonlan** [comment]
This has been fixed in the 1.3.0 release.
