### ISSUE TITLE
Enhancement needed: caching of the DataKey encryption/decryption

### ISSUE THREAD

**Issue by pravsingh** [awslabs/aws-encryption-sdk-java#20]
once we have https://github.com/awslabs/aws-encryption-sdk-java/issues/19 implemented, we could try adding cache layer to speedup the operations.

The caching (prefer in memory Guava as default cache provider) could also be very useful where the encryption and decryption of the same DataKey is requested.

**Comment by gregsterin** [comment]
+1. This would be super useful for me. Having a network call for each encrypt/decrypt call make this SDK too slow for my use case currently.

**Comment by mattsb42-aws** [comment]
Please see this forum thread[1] for more information on data key caching, and please feel free to reach out to me there for more information about how it might help your use case.

[1] https://forums.aws.amazon.com/thread.jspa?threadID=257153

**Comment by bdonlan** [comment]
Data key caching has been released as part of the 1.3.0 release.

**Comment by pravsingh** [comment]
awesome. thank you!
