### ISSUE TITLE
Encryption uses "key/" ARN and not the "alias/" ARN

### ISSUE THREAD

**Issue by michaelajr** [awslabs/aws-encryption-sdk-java#3]
This is problematic when trying to provide a PolicyDocument to an instance profile. I need to allow decrypt privileges the key/\* ARNs instead of the alias/\* ARNs. Impossible to programmatically do that. Would be much better if I could allows decrypt privileges to the alias/\* ARNs as I can easily construct those.

**Comment by SalusaSecondus** [comment]
If I understand correctly, this is a change you'd like to see to KMS directly rather than to the encryption sdk. Is that correct?

If so, it is definitely a request we've heard before and are aware of, but this isn't the proper place to track it.

**Comment by michaelajr** [comment]
Not sure. This issue seems to be in the SDK (from my POV). I use the alias in the SDK to encrypt. But I need the full key ARN to decrypt. Seems odd.

**Comment by michaelajr** [comment]
Also seems odd that to decrypt - I need privileges to ALL the keys used to encrypt - not just the one in my region.

**Comment by michaelajr** [comment]
But maybe that is a KMS issue. If so, I can move this there.

**Comment by SalusaSecondus** [comment]
Permissions cannot be given to Aliases,they can only be given to keys. This is a limitation of KMS.

You should only need permission to a single key (ideally the one in your region) to successfully decrypt. I'll look into this.

**Comment by housejester** [comment]
Perhaps related to this (especially given @michaelajr's second comment), is that if you follow the recommendation in the "Get Started" example in the readme, then it is impossible to use an alias. The example does:
```
if (!decryptResult.getMasterKeyIds().get(0).equals(keyArn)) {
```
but, once decrypted, the decrypt result has the actual master key id, and not the alias. What I'd like to be able to do is resolve the alias to the actual keyArn, then do the "expected master key matches" check with the actual resolved id. better yet, it would be helpful to be able to ask the result to do so. ie:
```
if (!decryptResult.usesMasterKey(keyArn)) {
```
and have that method internally resolve the given arn if it is an alias.

For now, my workaround is I had to subclass `KmsMasterKeyProvider`, and create the AWSKMSClient myself (b/c it is expensive, and don't want to have to do it twice), and then do a `describeKeys` call to resolve an alias.

**Comment by bdonlan** [comment]
Merging into tracking issue #27 for supporting alias resolution on decrypt. Note that we won't be able to do anything about the lack of alias policies on the Encryption SDK side.
