### ISSUE TITLE
KmsMasterKeyProvider region should default to the value found in ~/.aws/config

### ISSUE THREAD

**Issue by austinmoore-** [awslabs/aws-encryption-sdk-java#5]
When `KmsMasterKeyProvider` is constructed without a region it uses`Region.getRegion(Regions.DEFAULT_REGION)` as seen below:

```java
public KmsMasterKeyProvider(final AWSCredentials creds) {
    this(new StaticCredentialsProvider(creds), Region.getRegion(Regions.DEFAULT_REGION), new ClientConfiguration(),
            Collections.<String> emptyList());
}
```

In boto3, if a region is not specified, it tries to use the value for region found in `~/.aws/config`. http://boto3.readthedocs.io/en/latest/guide/configuration.html#configuration-file

In my opinion, the AWS Encryption SDK should behave similarly, falling back on `Regions.DEFAULT_REGION` if `~/.aws/config` cannot be used.

**Comment by SalusaSecondus** [comment]
I think that this is out of scope for the aws-encryption-sdk-java as I believe that it will use the same default that the rest of the Java SDK will use.

**Comment by austinmoore-** [comment]
Oh, my mistake. I assumed the Java SDK would use `~/.aws/config` as well. For now, I've implemented what I needed with `new AwsProfileRegionProvider().getRegion()`.

It looks like [AwsProfileRegionProvider](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/AwsProfileRegionProvider.java) was just added, so maybe the functionality seen in Boto3 will be coming to the Java SDK.

Anyway, I'm gonna close this ticket and this can be revisited later if the Java SDK starts using `~/.aws/config`. Thanks!

**Comment by SalusaSecondus** [comment]
Mind opening an issue (or submitting a pull request) to move over to the new AWSKMSClientBuilder? That sounds like a useful change.

**Comment by austinmoore-** [comment]
Sure thing. I'll make a PR with the move to `AWSKMSClientBuilder` soon.
