### ISSUE TITLE
0.0.1-SNAPSHOT release

### ISSUE THREAD

**Issue by ggonchar** [awslabs/aws-encryption-sdk-java#8]
I want to use aws-encryption-sdk in my project with currently available functionality. So I want to stick to 0.0.1 and update only intentionally by updating version. Therefore could you please provide 0.0.1 and switch development to 0.0.2-SNAPSHOT if possible

**Comment by SalusaSecondus** [comment]
I don't understand your request. 0.0.1-SNAPSHOT has been released. Any future releases will be under new versions.

**Comment by shrikantdange1208** [comment]
@SalusaSecondus I am facing the same issue. Is there a plan to push a stable 0.0.1 version without SNAPSHOT?

**Comment by SalusaSecondus** [comment]
0.0.1-SNAPSHOT will not be updated. I'll do a 0.0.1 release shortly.

**Comment by shrikantdange1208** [comment]
@SalusaSecondus Is there any approximate date for 0.0.1 release?

**Comment by srp** [comment]
@SalusaSecondus this is also causing me problems, and update on pushing the non-snapshot 0.0.1 release?

**Comment by SalusaSecondus** [comment]
I apologize for the delay. I'll try to get it out this week.
