### ISSUE TITLE
AWSKMSException: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by behrangsa** [awslabs/aws-encryption-sdk-java#9]
When running this sample code:

```java
public class InvalidSecurityToken {

    public static void main(String[] args) throws NoSuchAlgorithmException, InvalidKeySpecException, IOException {
        final String accessKey = requiredEnvVar("ACCESS_KEY");
        final String secretKey = requiredEnvVar("SECRET_KEY");
        final String customerMasterKey = requiredEnvVar("CMK");
        final String region = requiredEnvVar("REGION");

        final AwsCrypto awsCrypto = new AwsCrypto();

        final KmsMasterKeyProvider masterKeyProvider = new KmsMasterKeyProvider(
                new BasicAWSCredentials(accessKey, secretKey),
                customerMasterKey
        );

        masterKeyProvider.setRegion(Region.getRegion(Regions.fromName(region)));

        final String plainText = "Hello, World!";

        final Map<String, String> context = Collections.singletonMap("Context", "Bug Report");

        final byte[] encryptedResult = awsCrypto.encryptData(
                masterKeyProvider,
                plainText.getBytes(),
                context
        ).getResult();

        System.out.println(Base64.getEncoder().encodeToString(encryptedResult));
    }

    private static String requiredEnvVar(String name) {
        final String envVar = System.getenv(name);

        if (envVar == null || envVar.trim().length() == 0) {
            throw new RuntimeException("Missing environment variable: " + name);
        }

        System.out.printf("%s = %s\n", name, envVar);

        return envVar;
    }

}
```

I am getting the following error:

```
Exception in thread "main" com.amazonaws.services.kms.model.AWSKMSException: The security token included in the request is invalid. (Service: AWSKMS; Status Code: 400; Error Code: UnrecognizedClientException; Request ID: b3624a4d-6795-11e6-9331-fd581625bf3e)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1386)
	...
```

The request ID (`b3624a4d-6795-11e6-9331-fd581625bf3e`) might be handy to figure out if I am doing something wrong on my end or if this is a bug in the SDK.

* For `CMK`, I tried both an alias (e.g. `alias/foo`) as well as an ARN. The `CMK` is already created and the used ACCESS/SECRET key combo have permission to use it.
* And the region I am using in this scenario is `ap-southeast-2`.

I have attached a small app that can be used to reproduce the issue:

[bugreport.zip](https://github.com/awslabs/aws-encryption-sdk-java/files/428814/bugreport.zip)

**Comment by behrangsa** [comment]
Looks like I was using an incorrect ACCESS/SECRET key pair. I think the exception should convey the problem with a clearer message.

**Comment by jimiparekh** [comment]
Hello behrangsa,
I am trying to use a encryption key (using AWS Encryption SDK). I am getting the same error.
My key is like "arn:aws:kms:us-east-1:XXXXXXXXXX:_key/yyyyy-yyyy-yyyy-yyyy-yyyy"
I have set the environment variable 'AWS_ACCESS_KEY = arn:aws:kms:us-east-1:XXXXXXXXXX' and 'AWS_SECRET_KEY = key/yyyyy-yyyy-yyyy-yyyy-yyyy'.

I am getting error: Exception in thread "main" com.amazonaws.services.kms.model.AWSKMSException: The
security token included in the request is invalid. (Service: AWSKMS; Status Cod
e: 400; Error Code: UnrecognizedClientException; Request ID: 93d79101-e8c8-11e6-
af94-ed78adcea1db).

Can you please let me know what is the correct value for access_key and secret_key?

**Comment by SalusaSecondus** [comment]
@jimiparekh This is unrelated to the encryption SDK. The AWS_ACCESS_KEY and AWS_SECRET_KEY are the AWS credentials you use to call KMS (and other possible services).

**Comment by jimiparekh** [comment]
SalusaSecondus,
Thanks for your response. So you mean to say its my username/password which I use to login to AWS?

**Comment by SalusaSecondus** [comment]
@jimiparekh Not quite. The user-name password is what you use when you're logging into the console. The access_key/secret_key are programmatic credentials.  I recommend you read through [Understanding and Getting Your Security Credentials](https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html), especially the section related to **Access Keys**.
